  0%|          | 0/759 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159816'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511260'
KeyError: '511020'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511270'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159650'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159981'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511380'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159834'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159831'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159833'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159830'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159972'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159980'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159985'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511220'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511360'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511580'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159649'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159812'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511520'
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
Traceback (most recent call last):
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '511030'
KeyError: '511060'
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159651'
KeyError: '511010'
KeyError: '511180'
  0%|          | 1/759 [00:02<31:13,  2.47s/it]  0%|          | 2/759 [00:02<13:45,  1.09s/it]  0%|          | 3/759 [00:02<08:37,  1.46it/s]  3%|▎         | 23/759 [00:03<01:07, 10.98it/s]  6%|▌         | 45/759 [00:07<01:30,  7.86it/s]Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
Traceback (most recent call last):
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  8%|▊         | 63/759 [00:07<00:57, 12.12it/s]  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
  9%|▊         | 66/759 [00:07<00:54, 12.61it/s]KeyError: '159670'
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159697'
 89%|████████▉ | 679/759 [00:07<00:00, 312.20it/s]  File "/mnt/d/workspace/qtrade2/StockData.py", line 28, in get_stock_data
    df = ak.fund_etf_hist_em(symbol=code, period="daily", start_date="19900101",
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/akshare/fund/fund_etf_em.py", line 154, in fund_etf_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '513950'
KeyError: '513390'
 89%|████████▉ | 679/759 [00:20<00:00, 312.20it/s] 91%|█████████ | 690/759 [00:21<00:02, 29.62it/s] 100%|██████████| 759/759 [00:21<00:00, 35.02it/s]
Traceback (most recent call last):
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/zxl/anaconda3/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/zxl/anaconda3/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxl/anaconda3/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxl/anaconda3/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxl/anaconda3/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/zxl/anaconda3/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6bd845deb0>: Failed to establish a new connection: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='hq.sinajs.cn', port=80): Max retries exceeded with url: /rn=1682543434867&list=sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bd845deb0>: Failed to establish a new connection: [Errno 22] Invalid argument'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/workspace/qtrade2/qtrade.py", line 157, in <module>
    run_continue_down_strategy()
  File "/mnt/d/workspace/qtrade2/qtrade.py", line 117, in run_continue_down_strategy
    stock_dfs = s.get_all_data()
  File "/mnt/d/workspace/qtrade2/StockData.py", line 55, in get_all_data
    realtime_data = quotation.stocks(codes)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/easyquotation/basequotation.py", line 66, in stocks
    return self.real(stock_codes, prefix)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/easyquotation/basequotation.py", line 82, in real
    return self.get_stock_data(stock_list, prefix=prefix)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/easyquotation/basequotation.py", line 108, in get_stock_data
    res = self._fetch_stock_data(stock_list)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/easyquotation/basequotation.py", line 115, in _fetch_stock_data
    res = pool.map(self.get_stocks_by_range, stock_list)
  File "/home/zxl/anaconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zxl/anaconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/zxl/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/zxl/anaconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/easyquotation/basequotation.py", line 93, in get_stocks_by_range
    r = self._session.get(self.stock_api + params, headers=headers)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxl/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='hq.sinajs.cn', port=80): Max retries exceeded with url: /rn=1682543434867&list=sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390,sh510390 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bd845deb0>: Failed to establish a new connection: [Errno 22] Invalid argument'))
